export interface Country {
  name: string;
  iso: string;       // ISO 3166-1 alpha-2
  dialCode: string;  // e.g. "+44"
}

export const isoToFlag = (iso: string): string =>
  iso
    .toUpperCase()
    .split('')
    .map(c => String.fromCodePoint(c.charCodeAt(0) + 0x1f1a5))
    .join('');

export const COUNTRIES: Country[] = [
  { name: 'Afghanistan', iso: 'AF', dialCode: '+93' },
  { name: 'Albania', iso: 'AL', dialCode: '+355' },
  { name: 'Algeria', iso: 'DZ', dialCode: '+213' },
  { name: 'Argentina', iso: 'AR', dialCode: '+54' },
  { name: 'Australia', iso: 'AU', dialCode: '+61' },
  { name: 'Austria', iso: 'AT', dialCode: '+43' },
  { name: 'Azerbaijan', iso: 'AZ', dialCode: '+994' },
  { name: 'Bahrain', iso: 'BH', dialCode: '+973' },
  { name: 'Bangladesh', iso: 'BD', dialCode: '+880' },
  { name: 'Belarus', iso: 'BY', dialCode: '+375' },
  { name: 'Belgium', iso: 'BE', dialCode: '+32' },
  { name: 'Bolivia', iso: 'BO', dialCode: '+591' },
  { name: 'Bosnia & Herzegovina', iso: 'BA', dialCode: '+387' },
  { name: 'Brazil', iso: 'BR', dialCode: '+55' },
  { name: 'Bulgaria', iso: 'BG', dialCode: '+359' },
  { name: 'Cambodia', iso: 'KH', dialCode: '+855' },
  { name: 'Cameroon', iso: 'CM', dialCode: '+237' },
  { name: 'Canada', iso: 'CA', dialCode: '+1' },
  { name: 'Chile', iso: 'CL', dialCode: '+56' },
  { name: 'China', iso: 'CN', dialCode: '+86' },
  { name: 'Colombia', iso: 'CO', dialCode: '+57' },
  { name: 'Croatia', iso: 'HR', dialCode: '+385' },
  { name: 'Cuba', iso: 'CU', dialCode: '+53' },
  { name: 'Cyprus', iso: 'CY', dialCode: '+357' },
  { name: 'Czech Republic', iso: 'CZ', dialCode: '+420' },
  { name: 'Denmark', iso: 'DK', dialCode: '+45' },
  { name: 'Ecuador', iso: 'EC', dialCode: '+593' },
  { name: 'Egypt', iso: 'EG', dialCode: '+20' },
  { name: 'Ethiopia', iso: 'ET', dialCode: '+251' },
  { name: 'Finland', iso: 'FI', dialCode: '+358' },
  { name: 'France', iso: 'FR', dialCode: '+33' },
  { name: 'Georgia', iso: 'GE', dialCode: '+995' },
  { name: 'Germany', iso: 'DE', dialCode: '+49' },
  { name: 'Ghana', iso: 'GH', dialCode: '+233' },
  { name: 'Greece', iso: 'GR', dialCode: '+30' },
  { name: 'Guatemala', iso: 'GT', dialCode: '+502' },
  { name: 'Hong Kong', iso: 'HK', dialCode: '+852' },
  { name: 'Hungary', iso: 'HU', dialCode: '+36' },
  { name: 'India', iso: 'IN', dialCode: '+91' },
  { name: 'Indonesia', iso: 'ID', dialCode: '+62' },
  { name: 'Iran', iso: 'IR', dialCode: '+98' },
  { name: 'Iraq', iso: 'IQ', dialCode: '+964' },
  { name: 'Ireland', iso: 'IE', dialCode: '+353' },
  { name: 'Israel', iso: 'IL', dialCode: '+972' },
  { name: 'Italy', iso: 'IT', dialCode: '+39' },
  { name: 'Japan', iso: 'JP', dialCode: '+81' },
  { name: 'Jordan', iso: 'JO', dialCode: '+962' },
  { name: 'Kazakhstan', iso: 'KZ', dialCode: '+7' },
  { name: 'Kenya', iso: 'KE', dialCode: '+254' },
  { name: 'Kuwait', iso: 'KW', dialCode: '+965' },
  { name: 'Lebanon', iso: 'LB', dialCode: '+961' },
  { name: 'Libya', iso: 'LY', dialCode: '+218' },
  { name: 'Malaysia', iso: 'MY', dialCode: '+60' },
  { name: 'Mexico', iso: 'MX', dialCode: '+52' },
  { name: 'Morocco', iso: 'MA', dialCode: '+212' },
  { name: 'Myanmar', iso: 'MM', dialCode: '+95' },
  { name: 'Nepal', iso: 'NP', dialCode: '+977' },
  { name: 'Netherlands', iso: 'NL', dialCode: '+31' },
  { name: 'New Zealand', iso: 'NZ', dialCode: '+64' },
  { name: 'Nigeria', iso: 'NG', dialCode: '+234' },
  { name: 'Norway', iso: 'NO', dialCode: '+47' },
  { name: 'Oman', iso: 'OM', dialCode: '+968' },
  { name: 'Pakistan', iso: 'PK', dialCode: '+92' },
  { name: 'Palestine', iso: 'PS', dialCode: '+970' },
  { name: 'Peru', iso: 'PE', dialCode: '+51' },
  { name: 'Philippines', iso: 'PH', dialCode: '+63' },
  { name: 'Poland', iso: 'PL', dialCode: '+48' },
  { name: 'Portugal', iso: 'PT', dialCode: '+351' },
  { name: 'Qatar', iso: 'QA', dialCode: '+974' },
  { name: 'Romania', iso: 'RO', dialCode: '+40' },
  { name: 'Russia', iso: 'RU', dialCode: '+7' },
  { name: 'Saudi Arabia', iso: 'SA', dialCode: '+966' },
  { name: 'Senegal', iso: 'SN', dialCode: '+221' },
  { name: 'Serbia', iso: 'RS', dialCode: '+381' },
  { name: 'Singapore', iso: 'SG', dialCode: '+65' },
  { name: 'Slovakia', iso: 'SK', dialCode: '+421' },
  { name: 'South Africa', iso: 'ZA', dialCode: '+27' },
  { name: 'South Korea', iso: 'KR', dialCode: '+82' },
  { name: 'Spain', iso: 'ES', dialCode: '+34' },
  { name: 'Sri Lanka', iso: 'LK', dialCode: '+94' },
  { name: 'Sudan', iso: 'SD', dialCode: '+249' },
  { name: 'Sweden', iso: 'SE', dialCode: '+46' },
  { name: 'Switzerland', iso: 'CH', dialCode: '+41' },
  { name: 'Syria', iso: 'SY', dialCode: '+963' },
  { name: 'Taiwan', iso: 'TW', dialCode: '+886' },
  { name: 'Tanzania', iso: 'TZ', dialCode: '+255' },
  { name: 'Thailand', iso: 'TH', dialCode: '+66' },
  { name: 'Tunisia', iso: 'TN', dialCode: '+216' },
  { name: 'Turkey', iso: 'TR', dialCode: '+90' },
  { name: 'Uganda', iso: 'UG', dialCode: '+256' },
  { name: 'Ukraine', iso: 'UA', dialCode: '+380' },
  { name: 'United Arab Emirates', iso: 'AE', dialCode: '+971' },
  { name: 'United Kingdom', iso: 'GB', dialCode: '+44' },
  { name: 'United States', iso: 'US', dialCode: '+1' },
  { name: 'Uruguay', iso: 'UY', dialCode: '+598' },
  { name: 'Uzbekistan', iso: 'UZ', dialCode: '+998' },
  { name: 'Venezuela', iso: 'VE', dialCode: '+58' },
  { name: 'Vietnam', iso: 'VN', dialCode: '+84' },
  { name: 'Yemen', iso: 'YE', dialCode: '+967' },
  { name: 'Zimbabwe', iso: 'ZW', dialCode: '+263' },
];

export const DEFAULT_COUNTRY = COUNTRIES.find(c => c.iso === 'GB')!;
